# coding: utf-8
module ApplicationHelper

  def states_for_select
    [
      'AC',
      'AL',
      'AM',
      'AP',
      'BA',
      'CE',
      'DF',
      'ES',
      'GO',
      'MA',
      'MG',
      'MT',
      'PA',
      'PB',
      'PE',
      'PI',
      'PR',
      'RJ',
      'RN',
      'RO',
      'RR',
      'RS',
      'SC',
      'SE',
      'SP',
      'TO'
    ]
  end

  def initial_colaborators
    [
      'Adriana Teixeira Estellita Lins',
      'Alessandra Orofino Poubel',
      'Alexandre Warwar',
      'Alice Kasznar Feghali',
      'Alice Oliveira',
      'Alyne Rolin de Araujo',
      'Ana Luísa Corrêa da Costa Azêdo',
      'André Kano',
      'Anna Leticia Mariani Lacerda',
      'Arlindo Saraiva Pereira Junior',
      'Arminio Fraga Neto',
      'Arthur Aguillar',
      'Bernardo Castro',
      'Bruno Queiroz Cunha',
      'Cacá Neutzling',
      'Carlos Arthur Leite da Veiga',
      'Carlos Eduardo Lopes da Silva',
      'Carlos Sandes Ehlers',
      'Carolina de Moraes Rego Naine Reis',
      'Carolina Franco Afonso',
      'Clara Leitão Abreu',
      'Daniela Orofino',
      'Dirceu Barquette Filho',
      'Dorly Dias Curvello Neto',
      'Dulce Helena Gonçalves Orofino',
      'Edda S. de Freitas e Castro',
      'Eloisa Vidal Rosas',
      'Eurydice Botelho Moschkovich',
      'Fabiano de Souza Pereira',
      'Farol da Barra Participações Ltda.',
      'Felipe Areas ',
      'Fernanda Whately',
      'Fernando Pinheiro da Silva',
      'George Leimann',
      'Gilberto Sayão da Silva',
      'Guilherme Augusto Frering ',
      'Heloisa Arruda',
      #'Icatu Holding S.A.',
      #'Instituto Arapyaú de Educação e Desenvolvimento Sustentável ',
      'Iracema Fanzeres Langsch Dutra',
      #'Itaú Unibanco S.A. ',
      'João de Lima Pessanha',
      'João Parodi',
      'John Raschle Junior',
      'José Antônio e Souza',
      'Julia Esteves Abreu',
      'Juliana de Souza Pedrosa',
      'Julio Cesar de Souza',
      'Kristina Michahelles',
      'Laura Uplinger',
      'Leila Jacyntho Dutra',
      'Leonardo do Carmo Alves',
      'Leonardo Elói',
      'Lucas Arantes Botelho Briglia Habib',
      'Lucia Helena Sampaio',
      'Luiz Fonseca',
      'Luiz Orenstein',
      'Manoel Corrêa do Lago',
      'Marcel Beiner',
      'Marcelo de Toledo Campanér',
      'Marcos Huet Nioac de Salles',
      'Maria Alcione Coelho',
      'Maria Elizabeth Pinto',
      'Maria Inês Carsalade Martins',
      'Mariana Moschkovich Athayde',
      'Miguel Lago',
      'Miriam de Andrade Levy',
      'Mônica Coelho Mitkiewicz',
      'Nicolas Iensen',
      'Nina Saroldi',
      'Octavio de Souza Dantas',
      'Orlando Hill',
      'Paulo Roberto Rodrigues de Souza',
      'Pedro Cavalcanti Ferreira',
      'Rafael Rezende',
      'Raul F. Carvalho Miranda',
      'Raulino Oliveira',
      'Rita Lamy Freund',
      'Rodrigo de Assis Fialho',
      'Rosalie Marin',
      'Rosangela Maciel de Araujo Passos',
      'Rubem Nunes Galvarro Vianna',
      'Sandra Lucia Correia Lima Fortes',
      'Tatiana Leite',
      'Thales Eduardo Soares Martins',
      'Valeska Gadelha',
      'Vicente Miller de Oliveira',
      'Vitor Gurgel de Medeiros',
      'Vitor Miranda ',
      'Vivian Moraes Alonso',
      'Viviane da Rocha Vieira',
      'Waldemar Falcão Neto',
      'Wilson Malafaia Peixoto',
      'Yasmin Youssef'
    ]
  end

end
